spring:
  datasource:
    url: jdbc:mariadb://wouldumarryme.ciq19zaa9d7l.ap-northeast-2.rds.amazonaws.com:3306/wouldumarrymedb?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: ssafyb106 #root
    driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: utf-8
  #Multipart File 용량 설정
  servlet:
    multipart:
      max-file-size:  50MB
      max-request-size: 50MB



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

# AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAY3BUOWP6Y52BJTNU
      secretKey: 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
    s3:
      bucket: wouldumarryme
    region:
      static: ap-northeast-2
    stack:
      auto: false

#spring aws 경로 설정
server:
  servlet:
    context-path: /api
  port: 8080



